name: Markdown CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdown-check:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v4

      - name: Markdownファイル一覧を表示
        run: |
          echo "Markdown files:"
          find . -name "*.md"